### ISSUE TITLE
Vibrator not working

### ISSUE THREAD

**Issue by schmittlauch** [sailfish-on-fxtecpro1/droid-config-t5#36]
The vibrator of the device, working fine under Android, is not working under Sailfish OS:
Neither the CSD test nor any other action supposed to cause vibration (pulley menu, keyboard) result in vibration.

Build 3.3.0.16 on testing channel, freshly flashed

**Comment by Kabouik** [comment]
Weird, no issue for me. Did you try to `zypper refresh` and `zypper update`?

**Comment by schmittlauch** [comment]
`zypper ref && version --dup` didn't install any updates.
And yes, I flashed sailfishos-t5-release-3.3.0.16-devel-20200507.zip directly.

**Comment by piggz** [comment]
@schmittlauch Can you give output of
rpm -qi ngfd-plugin-native-vibrator
and
cat /usr/share/ssu/features.d/adaptation-community.ini 
thx

As @Kabouik says, vibration is working for me.

**Comment by Kabouik** [comment]
After flashing the latest testing image on my phone, I have no vibration either. Same in the Components app, Haptic submenu, none of the actions will trigger a vibration.

Since December, I was just upgrading SFOS at new releases but did not reflash (or just for short tests, but I didn't notice this at the time). 

```
[nemo@Pro1 ~]$ rpm -qi ngfd-plugin-native-vibrator
Name        : ngfd-plugin-native-vibrator
Version     : 1.2
Release     : 1.3.1.jolla
Architecture: armv7hl
Install Date: Fri Jul  3 13:05:19 2020
Group       : System/Daemons
Size        : 41679
License     : LGPLv2+
Signature   : DSA/SHA1, Fri Mar 27 10:05:27 2020, Key ID 68ebdd7df2633ee0
Source RPM  : ngfd-plugin-native-vibrator-1.2-1.3.1.jolla.src.rpm
Build Date  : Fri Mar 27 10:05:18 2020
Build Host  : phost9
Relocations : (not relocatable)
Vendor      : meego
URL         : https://github.com/mer-hybris/ngfd-plugin-droid-vibrator
Summary     : Droid Vibrator native plugin for ngfd
Description :
This package contains the Droid Vibrator plugin
for the non-graphical feedback daemon.
```

```
[nemo@Pro1 ~]$  cat /usr/share/ssu/features.d/adaptation-community.ini
[adaptation-community]
repos = adaptation-community
pattern = Feature community adaptation
description = Enable ssu for community ports

[repositories]
adaptation-community = http://repo.merproject.org/obs/nemo:/testing:/hw:/fxtec:/t5/sailfishos_%(release)/
```

**Comment by piggz** [comment]
Thanks, can you get me journal logs please.

**Comment by Kabouik** [comment]
```
[nemo@Pro1 ~]$ devel-su journalctl -xe
Password: 
-- Logs begin at Sat 2020-07-18 13:37:38 CEST, end at Sat 2020-07-18 13:45:09 CEST. --
Jul 18 13:45:04 Pro1 kernel: spi_qsd c1b9000.spi: msm_spi_clock_set: no match found for requested clock frequen
cy:400000
Jul 18 13:45:04 Pro1 kernel: spi_qsd c1b9000.spi: msm_spi_clock_set: no match found for requested clock frequen
cy:400000
Jul 18 13:45:04 Pro1 kernel: spi_qsd c1b9000.spi: msm_spi_clock_set: no match found for requested clock frequen
cy:400000
Jul 18 13:45:04 Pro1 kernel: spi_qsd c1b9000.spi: msm_spi_clock_set: no match found for requested clock frequen
cy:400000
Jul 18 13:45:04 Pro1 kernel: spi_qsd c1b9000.spi: msm_spi_clock_set: no match found for requested clock frequen
cy:400000
Jul 18 13:45:04 Pro1 kernel: spi_qsd c1b9000.spi: msm_spi_clock_set: no match found for requested clock frequen
cy:400000
Jul 18 13:45:04 Pro1 kernel: spi_qsd c1b9000.spi: msm_spi_clock_set: no match found for requested clock frequen
cy:400000
Jul 18 13:45:04 Pro1 kernel: spi_qsd c1b9000.spi: msm_spi_clock_set: no match found for requested clock frequen
cy:400000
Jul 18 13:45:04 Pro1 kernel: spi_qsd c1b9000.spi: msm_spi_clock_set: no match found for requested clock frequen
cy:400000
Jul 18 13:45:04 Pro1 kernel: spi_qsd c1b9000.spi: msm_spi_clock_set: no match found for requested clock frequen
cy:400000
Jul 18 13:45:04 Pro1 kernel: Freezing user space processes ... (elapsed 0.014 seconds) done.
Jul 18 13:45:04 Pro1 kernel: Freezing remaining freezable tasks ... (elapsed 0.005 seconds) done.
Jul 18 13:45:04 Pro1 kernel: PM: Suspending system (mem)
Jul 18 13:45:04 Pro1 kernel: Suspending console(s) (use no_console_suspend to debug)
Jul 18 13:45:04 Pro1 kernel: R0: [kworker/u16:2][101992097797] [11:45:04.105060]  wlan: [90:I :HDD] hdd_suspend_wlan:
 1298: WLAN being suspended by OS
Jul 18 13:45:04 Pro1 kernel: R0: [kworker/u16:2][101992098143] [11:45:04.105078]  wlan: [90:I :HDD] hdd_suspend_wlan:
 1318: Disabling queues for dev mode QDF_STA_MODE
Jul 18 13:45:04 Pro1 kernel: R0: [kworker/u16:2][101992106605] [11:45:04.105519]  wlan: [90:I :HDD] hdd_suspend_wlan:
 1318: Disabling queues for dev mode QDF_P2P_DEVICE_MODE
Jul 18 13:45:04 Pro1 kernel: <blestech_fp>[bf_suspend:1197]  ++
Jul 18 13:45:04 Pro1 kernel: <blestech_fp>[bf_suspend:1202]
Jul 18 13:45:04 Pro1 kernel: R0: [kworker/u16:14][101992373924] [11:45:04.119442]  wlan: [8732:I :HDD] __wlan_hdd_bus
_suspend: 671: starting bus suspend; event:2, flags:0
Jul 18 13:45:04 Pro1 kernel: R0: [kworker/u16:14][101992375490] [11:45:04.119523]  wlan: [8732:I :WMI] suspend type: 
WOW_IFACE_PAUSE_DISABLED
Jul 18 13:45:04 Pro1 kernel: R0: [kworker/u16:14][101992379523] [11:45:04.119733]  wlan: [8732:I :HIF] hif_snoc_setup
_wakeup_sources: expecting wake from ce 2, irq 116 enable 1
Jul 18 13:45:04 Pro1 kernel: R0: [kworker/u16:14][101992379750] [11:45:04.119745]  wlan: [8732:I :HDD] __wlan_hdd_bus
_suspend: 715: bus suspend succeeded
Jul 18 13:45:04 Pro1 kernel: PM: suspend of devices complete after 24.972 msecs
Jul 18 13:45:04 Pro1 kernel: PM: late suspend of devices complete after 6.014 msecs
Jul 18 13:45:04 Pro1 kernel: R0: [kworker/u16:14][101992798260] [11:45:04.141543]  wlan: [8732:I :HDD] __wlan_hdd_bus
_suspend_noirq: 774: start bus_suspend_noirq
Jul 18 13:45:04 Pro1 kernel: R0: [kworker/u16:14][101992798807] [11:45:04.141571]  wlan: [8732:I :HDD] __wlan_hdd_bus
_suspend_noirq: 807: bus_suspend_noirq done
Jul 18 13:45:04 Pro1 kernel: PM: noirq suspend of devices complete after 6.964 msecs
Jul 18 13:45:04 Pro1 kernel: Disabling non-boot CPUs ...
Jul 18 13:45:04 Pro1 kernel: CPU3: update max cpu_capacity 1024
Jul 18 13:45:04 Pro1 kernel: CPU3: update max cpu_capacity 1024
Jul 18 13:45:04 Pro1 kernel: CPU0: update max cpu_capacity 1024
Jul 18 13:45:04 Pro1 kernel: CPU0: update max cpu_capacity 1024
Jul 18 13:45:04 Pro1 kernel: CPU0: update max cpu_capacity 1024
Jul 18 13:45:04 Pro1 kernel: CPU0: update max cpu_capacity 1024
Jul 18 13:45:04 Pro1 kernel: suspend ns:    1819789472447        suspend cycles:     101997618473
Jul 18 13:45:04 Pro1 kernel: resume cycles:     101998779421
```

**Comment by Kabouik** [comment]
Interestingly, I tried restoring a TWRP backup of my full SFOS system from somewhere in March, and vibration is working fine. This is the same device as above. I'll try upgrading now and see if vibration is still here afterwards.

**Comment by piggz** [comment]
thanks, if i get a chance tonight i will switch my device to the testing: repo and see what happens

**Comment by piggz** [comment]
can you give
rpm -qi qt5-feedback-haptics-native-vibrator 
thx

**Comment by Kabouik** [comment]
Are you asking that to @schmittlauch or me? Mine has vibration now with the restored TWRP backup (and upgrade is still ongoing, my connection is slow).

**Comment by piggz** [comment]
I have just switched to the testing: repo and vibration is still working :/

**Comment by Kabouik** [comment]
I still had vibration on my other phone on the testing branch after a `zypper dup` so that's consistent. However SFOS was first installed when there were only devel images, and I later switched to testing by editing `adaptation-community.ini`. 

There seems to be a difference between flashing directly one of the newest CI images, or upgrading SFOS from command line when it has already been installed from a previous CI image. I wanted to try several images, but ` sailfishos-t5-release-3.3.0.16-devel-20200506` seemed to be broken (resolution issue, everything was either tiny or not showing at all, so I couldn't go into menus to test vibration). 

Is it possible that there would be something that installs with devel and stays configured as is even after switching to testing, but doesn't happen when flashing testing directly?

restoring an older backup or upgrading SFOS flashed from

**Comment by schmittlauch** [comment]
@piggz I seem to have a newer release:

```console
$ rpm -qi qt5-feedback-haptics-native-vibrator
Name        : qt5-feedback-haptics-native-vibrator
Version     : 0.2.0
Release     : 1.4.1.jolla
Architecture: armv7hl
Install Date: Thu May  7 14:14:28 2020
Group       : System/Plugins
Size        : 26525
License     : LGPLv2.1
Signature   : DSA/SHA1, Fri Mar 27 10:50:01 2020, Key ID 68ebdd7df2633ee0
Source RPM  : qt5-feedback-haptics-native-vibrator-0.2.0-1.4.1.jolla.src.rpm
Build Date  : Fri Mar 27 10:49:37 2020
Build Host  : phost6
Relocations : (not relocatable)
Vendor      : meego
URL         : https://github.com/mer-hybris/qt-mobility-haptics-droid-vibrator
Summary     : Haptic feedback plugin using native vibrator
Description :
Haptic feedback plugin using native vibrator.
```

**Comment by schmittlauch** [comment]
Also for completeness sake, my current repos and their releases:

```
$ ssu lr
WARNING: ssu.ini does not seem to be writable. Setting values might not work.
Enabled repositories (global): 
 - adaptation-community        ... http://repo.merproject.org/obs/nemo:/testing:/hw:/fxtec:/t5/sailfishos_3.3.0.16/
 - adaptation-community-common ... http://repo.merproject.org/obs/nemo:/testing:/hw:/common/sailfishos_3.3.0.16/
 - aliendalvik                 ... https://store-repository.jolla.com/releases/3.3.0.16/aliendalvik/t5/
 - apps                        ... https://releases.jolla.com/jolla-apps/3.3.0.16/armv7hl/
 - hotfixes                    ... https://releases.jolla.com/releases/3.3.0.16/hotfixes/armv7hl/
 - jolla                       ... https://releases.jolla.com/releases/3.3.0.16/jolla/armv7hl/

Enabled repositories (user): 
 - openrepos-Kabouik           ... https://sailfish.openrepos.net/Kabouik/personal/main
 - openrepos-KeeperoftheKeys   ... https://sailfish.openrepos.net/KeeperoftheKeys/personal/main
 - openrepos-R1tschY           ... https://sailfish.openrepos.net/R1tschY/personal/main
 - openrepos-Simom             ... https://sailfish.openrepos.net/Simom/personal/main
 - openrepos-Sthocs            ... https://sailfish.openrepos.net/Sthocs/personal/main
 - openrepos-Wedmer            ... https://sailfish.openrepos.net/Wedmer/personal/main
 - openrepos-WerkWolf          ... https://sailfish.openrepos.net/WerkWolf/personal/main
 - openrepos-balta             ... https://sailfish.openrepos.net/balta/personal/main
 - openrepos-cnlpete           ... https://sailfish.openrepos.net/cnlpete/personal/main
 - openrepos-coderus           ... https://sailfish.openrepos.net/coderus/personal/main
 - openrepos-fifr              ... https://sailfish.openrepos.net/fifr/personal/main
 - openrepos-llelectronics     ... https://sailfish.openrepos.net/llelectronics/personal/main
 - openrepos-molan             ... https://sailfish.openrepos.net/molan/personal/main
 - openrepos-osetr             ... https://sailfish.openrepos.net/osetr/personal/main
 - openrepos-piggz             ... https://sailfish.openrepos.net/piggz/personal/main
 - openrepos-rinigus           ... https://sailfish.openrepos.net/rinigus/personal/main
 - openrepos-sailfish_keyboard ... https://sailfish.openrepos.net/sailfish_keyboard/personal/main
 - store                       ... https://store-repository.jolla.com/t5/armv7hl/?version=3.3.0.16

Disabled repositories (global, might be overridden by user config): 

Disabled repositories (user): 
 - home ... https://download.jollamobile.com/home:/honeybadger/latest_armv7hl/
```

**Comment by piggz** [comment]
@Kabouik @schmittlauch  on your non-working devices, can you give me the output of:
groups
as nemo user
thanks

**Comment by Kabouik** [comment]
I can't test on a device with no vibration anymore, but I'm in the `system` group on one with vibration working:

```
nemo tty video users sailfish-datetime sailfish-alarms sailfish-system ssu timed oneshot system bluetooth graphics input audio camera media media_rw mtp inet
```

**Comment by schmittlauch** [comment]
I get

```console
$ groups
nemo video users timed sailfish-datetime sailfish-alarms sailfish-system oneshot bluetooth graphics input audio camera media media_rw mtp inet
```

So in contrast to @Kabouik my nemo user is only member of `sailfish-system` but not of `system`.

**Comment by piggz** [comment]
I think this is fixed in the devel: repository.  Id be very happy if you are comfortable switching to devel: and testing it.
to do this, edit
/usr/share/ssu/features.d/adaptation-community.ini
and change the url line to:
adaptation-community = http://repo.merproject.org/obs/nemo:/devel:/hw:/fxtec:/t5/sailfish_latest_%(arch)/

Then do the same to 
/usr/share/ssu/features.d/adaptation-community-common.ini
and change the url line to
adaptation-community-common = http://repo.merproject.org/obs/nemo:/devel:/hw:/common/sailfish_latest_%(arch)/

Then, type
ssu ur
zypper ref
zypper dup
and keep fingers crossed :D

**Comment by schmittlauch** [comment]
I'm on the devel repo now, but after a reboot vibration is still not working and the group assignment looks the same:

```console
$ groups
nemo video users timed sailfish-datetime sailfish-alarms sailfish-system oneshot bluetooth graphics input audio camera media media_rw mtp inet
```

**Comment by piggz** [comment]
Ok, can you show the following:
rpm -qi droid-hal-t5
cat /init.rc
ls -lh /sys/class/timed_output/vibrator/
And finally, do you have aliendalvik installed, and if so
rpm -qi aliendalvik
Thanks

**Comment by schmittlauch** [comment]
```console
[nemo@Pro1 ~]$ rpm -qi droid-hal-t5
Name        : droid-hal-t5
Version     : 0.0.6
Release     : 202007202037
Architecture: armv7hl
Install Date: Tue Jul 21 18:17:54 2020
Group       : System
Size        : 61139781
License     : BSD-3-Clause
Signature   : (none)
Source RPM  : droid-hal-t5-0.0.6-202007202037.src.rpm
Build Date  : Mon Jul 20 22:38:21 2020
Build Host  : linux-f1uu
Relocations : (not relocatable)
Vendor      : fxtec
Summary     : Droid HAL package for t5
Description :
Droid HAL package for t5.
[nemo@Pro1 ~]$ cat /init.rc
# Copyright (C) 2012 The Android Open Source Project
#
# IMPORTANT: Do not create world writable files or directories.
# This is a common source of Android security bugs.
#

# this file is only necessary if your device is 32 bit and it is
# using the android kernel logger if your device is 64 bit defining
# LD_LIBRARY_PATH will break some binaries, since you cannot have both
# 32 bit libraries and 64 bit libraries in your LD_LIBRARY_PATH.
import /init.extraenv.${ro.product.cpu.abi}.rc
import /init.environ.rc
# Mer handles usb stuff
#import /init.usb.rc
import /init.${ro.hardware}.rc
import /vendor/etc/init/hw/init.${ro.hardware}.rc
import /init.${ro.zygote}.rc

on early-init
    # Set init and its forked children's oom_adj.
    write /proc/1/oom_score_adj -1000

    # Disable sysrq from keyboard
    write /proc/sys/kernel/sysrq 0

    # Set the security context of /adb_keys if present.
    restorecon /adb_keys

    # Set the security context of /postinstall if present.
    restorecon /postinstall

    # Mount cgroup mount point for cpu accounting
# Removed during droid-hal-device build :     mount cgroup none /acct nodev noexec nosuid cpuacct
    mkdir /acct/uid

    # start ueventd

on init
    sysclktz 0

    # Mix device-specific information into the entropy pool
    copy /proc/cmdline /dev/urandom
    copy /default.prop /dev/urandom

    #symlink /system/bin /bin
    #symlink /system/etc /etc

    loglevel 64

    # Backward compatibility.
    symlink /sys/kernel/debug /d

    # Link /vendor to /system/vendor for devices without a vendor partition.
    # hybris: in android 8 vendor is a seperate partition and our systemd
    # doesn't like if /vendor is a symlink and it cannot mount vendor to that.
    # symlink /system/vendor /vendor

    # Create energy-aware scheduler tuning nodes
    mkdir /dev/stune
# Removed during droid-hal-device build :     mount cgroup none /dev/stune nodev noexec nosuid schedtune
    mkdir /dev/stune/foreground
    mkdir /dev/stune/background
    mkdir /dev/stune/top-app
    mkdir /dev/stune/rt
    mkdir /dev/stune/audio-app
    chown system system /dev/stune
    chown system system /dev/stune/foreground
    chown system system /dev/stune/background
    chown system system /dev/stune/top-app
    chown system system /dev/stune/rt
    chown system system /dev/stune/audio-app
    chown system system /dev/stune/tasks
    chown system system /dev/stune/foreground/tasks
    chown system system /dev/stune/background/tasks
    chown system system /dev/stune/top-app/tasks
    chown system system /dev/stune/rt/tasks
    chown system system /dev/stune/audio-app/tasks
    chmod 0664 /dev/stune/tasks
    chmod 0664 /dev/stune/foreground/tasks
    chmod 0664 /dev/stune/background/tasks
    chmod 0664 /dev/stune/top-app/tasks
    chmod 0664 /dev/stune/rt/tasks
    chmod 0664 /dev/stune/audio-app/tasks

    restorecon_recursive /mnt

# Removed during droid-hal-device build :     mount configfs none /config nodev noexec nosuid
    chmod 0770 /config/sdcardfs
    chown system package_info /config/sdcardfs

    mkdir /mnt/secure 0700 root root
    mkdir /mnt/secure/asec 0700 root root
    mkdir /mnt/asec 0755 root system
    mkdir /mnt/obb 0755 root system
    mkdir /mnt/media_rw 0750 root media_rw
    mkdir /mnt/user 0755 root root
    mkdir /mnt/user/0 0755 root root
    mkdir /mnt/expand 0771 system system
    mkdir /mnt/appfuse 0711 root root

    # Storage views to support runtime permissions
    mkdir /mnt/runtime 0700 root root
    mkdir /mnt/runtime/default 0755 root root
    mkdir /mnt/runtime/default/self 0755 root root
    mkdir /mnt/runtime/read 0755 root root
    mkdir /mnt/runtime/read/self 0755 root root
    mkdir /mnt/runtime/write 0755 root root
    mkdir /mnt/runtime/write/self 0755 root root

    # Symlink to keep legacy apps working in multi-user world
    symlink /storage/self/primary /sdcard
    symlink /storage/self/primary /mnt/sdcard
    symlink /mnt/user/0/primary /mnt/runtime/default/self/primary

    write /proc/sys/kernel/panic_on_oops 1
    write /proc/sys/kernel/hung_task_timeout_secs 0

    #write /proc/cpu/alignment 4

    # scheduler tunables
    # Disable auto-scaling of scheduler tunables with hotplug. The tunables
    # will vary across devices in unpredictable ways if allowed to scale with
    # cpu cores.
    write /proc/sys/kernel/sched_tunable_scaling 0

    write /proc/sys/kernel/sched_latency_ns 10000000
    write /proc/sys/kernel/sched_wakeup_granularity_ns 2000000
    write /proc/sys/kernel/sched_child_runs_first 0

    write /proc/sys/kernel/randomize_va_space 2
    write /proc/sys/vm/mmap_min_addr 32768
    write /proc/sys/net/ipv4/ping_group_range "0 2147483647"
    write /proc/sys/net/unix/max_dgram_qlen 600
    write /proc/sys/kernel/sched_rt_runtime_us 950000
    write /proc/sys/kernel/sched_rt_period_us 1000000

    # Assign reasonable ceiling values for socket rcv/snd buffers.
    # These should almost always be overridden by the target per the
    # the corresponding technology maximums.
    write /proc/sys/net/core/rmem_max  262144
    write /proc/sys/net/core/wmem_max  262144

    # reflect fwmark from incoming packets onto generated replies
    write /proc/sys/net/ipv4/fwmark_reflect 1
    write /proc/sys/net/ipv6/fwmark_reflect 1

    # set fwmark on accepted sockets
    write /proc/sys/net/ipv4/tcp_fwmark_accept 1

    # disable icmp redirects
    write /proc/sys/net/ipv4/conf/all/accept_redirects 0
    write /proc/sys/net/ipv6/conf/all/accept_redirects 0

    # /proc/net/fib_trie leaks interface IP addresses
    chmod 0400 /proc/net/fib_trie

    # Create cgroup mount points for process groups
    mkdir /dev/cpuctl
# Removed during droid-hal-device build :     mount cgroup none /dev/cpuctl nodev noexec nosuid cpu
    chown system system /dev/cpuctl
    chown system system /dev/cpuctl/tasks
    chmod 0666 /dev/cpuctl/tasks
    write /dev/cpuctl/cpu.rt_period_us 1000000
    write /dev/cpuctl/cpu.rt_runtime_us 950000

    # sets up initial cpusets for ActivityManager
    mkdir /dev/cpuset
# Removed during droid-hal-device build :     mount cpuset none /dev/cpuset nodev noexec nosuid

    # this ensures that the cpusets are present and usable, but the device's
    # init.rc must actually set the correct cpus
    mkdir /dev/cpuset/foreground
    copy /dev/cpuset/cpus /dev/cpuset/foreground/cpus
    copy /dev/cpuset/mems /dev/cpuset/foreground/mems
    mkdir /dev/cpuset/background
    copy /dev/cpuset/cpus /dev/cpuset/background/cpus
    copy /dev/cpuset/mems /dev/cpuset/background/mems

    # system-background is for system tasks that should only run on
    # little cores, not on bigs
    # to be used only by init, so don't change system-bg permissions
    mkdir /dev/cpuset/system-background
    copy /dev/cpuset/cpus /dev/cpuset/system-background/cpus
    copy /dev/cpuset/mems /dev/cpuset/system-background/mems

    # restricted is for system tasks that are being throttled
    # due to screen off.
    mkdir /dev/cpuset/restricted
    copy /dev/cpuset/cpus /dev/cpuset/restricted/cpus
    copy /dev/cpuset/mems /dev/cpuset/restricted/mems

    mkdir /dev/cpuset/top-app
    copy /dev/cpuset/cpus /dev/cpuset/top-app/cpus
    copy /dev/cpuset/mems /dev/cpuset/top-app/mems

    mkdir /dev/cpuset/audio-app
    copy /dev/cpuset/cpus /dev/cpuset/audio-app/cpus
    copy /dev/cpuset/mems /dev/cpuset/audio-app/mems

    # change permissions for all cpusets we'll touch at runtime
    chown system system /dev/cpuset
    chown system system /dev/cpuset/foreground
    chown system system /dev/cpuset/background
    chown system system /dev/cpuset/system-background
    chown system system /dev/cpuset/top-app
    chown system system /dev/cpuset/audio-app
    chown system system /dev/cpuset/restricted
    chown system system /dev/cpuset/tasks
    chown system system /dev/cpuset/foreground/tasks
    chown system system /dev/cpuset/background/tasks
    chown system system /dev/cpuset/system-background/tasks
    chown system system /dev/cpuset/top-app/tasks
    chown system system /dev/cpuset/audio-app/tasks
    chown system system /dev/cpuset/restricted/tasks

    # set system-background to 0775 so SurfaceFlinger can touch it
    chmod 0775 /dev/cpuset/system-background

    chmod 0664 /dev/cpuset/foreground/tasks
    chmod 0664 /dev/cpuset/background/tasks
    chmod 0664 /dev/cpuset/system-background/tasks
    chmod 0664 /dev/cpuset/top-app/tasks
    chmod 0664 /dev/cpuset/audio-app/tasks
    chmod 0664 /dev/cpuset/restricted/tasks
    chmod 0664 /dev/cpuset/tasks


    # qtaguid will limit access to specific data based on group memberships.
    #   net_bw_acct grants impersonation of socket owners.
    #   net_bw_stats grants access to other apps' detailed tagged-socket stats.
    chown root net_bw_acct /proc/net/xt_qtaguid/ctrl
    chown root net_bw_stats /proc/net/xt_qtaguid/stats

    # Allow everybody to read the xt_qtaguid resource tracking misc dev.
    # This is needed by any process that uses socket tagging.
    chmod 0644 /dev/xt_qtaguid

    mkdir /dev/cg2_bpf
# Removed during droid-hal-device build :     mount cgroup2 cg2_bpf /dev/cg2_bpf nodev noexec nosuid
    chown root root /dev/cg2_bpf
    chmod 0600 /dev/cg2_bpf
# Removed during droid-hal-device build :     mount bpf bpf /sys/fs/bpf nodev noexec nosuid

    # Create location for fs_mgr to store abbreviated output from filesystem
    # checker programs.
    mkdir /dev/fscklogs 0770 root system

    # pstore/ramoops previous console log
# Removed during droid-hal-device build :     mount pstore pstore /sys/fs/pstore nodev noexec nosuid
    chown system log /sys/fs/pstore/console-ramoops
    chmod 0440 /sys/fs/pstore/console-ramoops
    chown system log /sys/fs/pstore/console-ramoops-0
    chmod 0440 /sys/fs/pstore/console-ramoops-0
    chown system log /sys/fs/pstore/pmsg-ramoops-0
    chmod 0440 /sys/fs/pstore/pmsg-ramoops-0

    # enable armv8_deprecated instruction hooks
    write /proc/sys/abi/swp 1

    # Linux's execveat() syscall may construct paths containing /dev/fd
    # expecting it to point to /proc/self/fd
    symlink /proc/self/fd /dev/fd

    export DOWNLOAD_CACHE /data/cache

    # set RLIMIT_NICE to allow priorities from 19 to -20
    setrlimit nice 40 40

    # Allow up to 32K FDs per process
    setrlimit nofile 32768 32768

    # This allows the ledtrig-transient properties to be created here so
    # that they can be chown'd to system:system later on boot
    write /sys/class/leds/vibrator/trigger "transient"

# Healthd can trigger a full boot from charger mode by signaling this
# property when the power button is held.
on property:sys.boot_from_charger_mode=1
    class_stop charger
    trigger late-init

on load_persist_props_action
    load_persist_props
    start logd
    start logd-reinit

# Indicate to fw loaders that the relevant mounts are up.
on firmware_mounts_complete
    rm /dev/.booting

# Mount filesystems and start core system services.
on late-init
    trigger early-fs

    # Mount fstab in init.{$device}.rc by mount_all command. Optional parameter
    # '--early' can be specified to skip entries with 'latemount'.
    # /system and /vendor must be mounted by the end of the fs stage,
    # while /data is optional.
    trigger factory-fs
    trigger fs
    trigger post-fs

    # Mount fstab in init.{$device}.rc by mount_all with '--late' parameter
    # to only mount entries with 'latemount'. This is needed if '--early' is
    # specified in the previous mount_all command on the fs stage.
    # With /system mounted and properties form /system + /factory available,
    # some services can be started.
    trigger late-fs

    # Now we can mount /data. File encryption requires keymaster to decrypt
    # /data, which in turn can only be loaded when system properties are present.
    trigger post-fs-data

    # Now we can start zygote for devices with file based encryption
    trigger zygote-start

    # Load persist properties and override properties (if enabled) from /data.
    trigger load_persist_props_action

    # Remove a file to wake up anything waiting for firmware.
    trigger firmware_mounts_complete

    trigger early-boot
    trigger boot
    trigger mmi

on post-fs
    # Load properties from
    #     /system/build.prop,
    #     /odm/build.prop,
    #     /vendor/build.prop and
    #     /factory/factory.prop
    load_system_props
    # start essential services
    start logd
    start servicemanager
    start hwservicemanager
    start vndservicemanager

    # Once everything is setup, no need to modify /.
    # The bind+ro combination avoids modifying any other mount flags.
    # mount rootfs rootfs / remount bind ro
    # Mount shared so changes propagate into child namespaces
    # mount rootfs rootfs / shared rec
    # Mount default storage into root namespace
    # mount none /mnt/runtime/default /storage bind rec
    # mount none none /storage slave rec

    # Make sure /sys/kernel/debug (if present) is labeled properly
    # Note that tracefs may be mounted under debug, so we need to cross filesystems
    restorecon --recursive --cross-filesystems /sys/kernel/debug

    # We chown/chmod /cache again so because mount is run as root + defaults
    chown system cache /cache
    chmod 0770 /cache
    # We restorecon /cache in case the cache partition has been reset.
    restorecon_recursive /cache

    # Create /cache/recovery in case it's not there. It'll also fix the odd
    # permissions if created by the recovery system.
    mkdir /cache/recovery 0770 system cache

    # Backup/restore mechanism uses the cache partition
    mkdir /cache/backup_stage 0700 system system
    mkdir /cache/backup 0700 system system

    #change permissions on vmallocinfo so we can grab it from bugreports
    chown root log /proc/vmallocinfo
    chmod 0440 /proc/vmallocinfo

    chown root log /proc/slabinfo
    chmod 0440 /proc/slabinfo

    #change permissions on kmsg & sysrq-trigger so bugreports can grab kthread stacks
    chown root system /proc/kmsg
    chmod 0440 /proc/kmsg
    chown root system /proc/sysrq-trigger
    chmod 0220 /proc/sysrq-trigger
    chown system log /proc/last_kmsg
    chmod 0440 /proc/last_kmsg

    # make the selinux kernel policy world-readable
    chmod 0444 /sys/fs/selinux/policy

    # create the lost+found directories, so as to enforce our permissions
    mkdir /cache/lost+found 0770 root root

    restorecon_recursive /metadata
    mkdir /metadata/vold
    chmod 0700 /metadata/vold

on late-fs
    # Ensure that tracefs has the correct permissions.
    # This does not work correctly if it is called in post-fs.
    chmod 0755 /sys/kernel/debug/tracing

    # HALs required before storage encryption can get unlocked (FBE/FDE)
    class_start early_hal

    # Check and mark a successful boot, before mounting userdata with mount_all.
    # No-op for non-A/B device.
    exec_start update_verifier_nonencrypted

on post-fs-data
    # We chown/chmod /data again so because mount is run as root + defaults
    chown system system /data
    chmod 0771 /data
    # We restorecon /data in case the userdata partition has been reset.
    restorecon /data

    # Make sure we have the device encryption key.
    start vold
    installkey /data

    # Start bootcharting as soon as possible after the data partition is
    # mounted to collect more data.
    mkdir /data/bootchart 0755 shell shell
    bootchart start

    # Avoid predictable entropy pool. Carry over entropy from previous boot.
    copy /data/system/entropy.dat /dev/urandom

    # create basic filesystem structure
    mkdir /data/misc 01771 system misc
    mkdir /data/misc/recovery 0770 system log
    copy /data/misc/recovery/ro.build.fingerprint /data/misc/recovery/ro.build.fingerprint.1
    chmod 0440 /data/misc/recovery/ro.build.fingerprint.1
    chown system log /data/misc/recovery/ro.build.fingerprint.1
    write /data/misc/recovery/ro.build.fingerprint ${ro.build.fingerprint}
    chmod 0440 /data/misc/recovery/ro.build.fingerprint
    chown system log /data/misc/recovery/ro.build.fingerprint
    mkdir /data/misc/recovery/proc 0770 system log
    copy /data/misc/recovery/proc/version /data/misc/recovery/proc/version.1
    chmod 0440 /data/misc/recovery/proc/version.1
    chown system log /data/misc/recovery/proc/version.1
    copy /proc/version /data/misc/recovery/proc/version
    chmod 0440 /data/misc/recovery/proc/version
    chown system log /data/misc/recovery/proc/version
    mkdir /data/misc/bluedroid 02770 bluetooth bluetooth
    # Fix the access permissions and group ownership for 'bt_config.conf'
    chmod 0660 /data/misc/bluedroid/bt_config.conf
    chown bluetooth bluetooth /data/misc/bluedroid/bt_config.conf
    mkdir /data/misc/bluetooth 0770 bluetooth bluetooth
    mkdir /data/misc/bluetooth/logs 0770 bluetooth bluetooth
    mkdir /data/misc/keystore 0700 keystore keystore
    mkdir /data/misc/gatekeeper 0700 system system
    mkdir /data/misc/keychain 0771 system system
    mkdir /data/misc/net 0750 root shell
    mkdir /data/misc/radio 0770 system radio
    mkdir /data/misc/sms 0770 system radio
    mkdir /data/misc/carrierid 0770 system radio
    mkdir /data/misc/apns 0770 system radio
    mkdir /data/misc/zoneinfo 0775 system system
    mkdir /data/misc/network_watchlist 0774 system system
    mkdir /data/misc/textclassifier 0771 system system
    mkdir /data/misc/vpn 0770 system vpn
    mkdir /data/misc/shared_relro 0771 shared_relro shared_relro
    mkdir /data/misc/systemkeys 0700 system system
    mkdir /data/misc/wifi 0770 wifi wifi
    mkdir /data/misc/wifi/sockets 0770 wifi wifi
    mkdir /data/misc/wifi/wpa_supplicant 0770 wifi wifi
    mkdir /data/misc/ethernet 0770 system system
    mkdir /data/misc/dhcp 0770 dhcp dhcp
    mkdir /data/misc/user 0771 root root
    mkdir /data/misc/perfprofd 0775 root root
    # give system access to wpa_supplicant.conf for backup and restore
    chmod 0660 /data/misc/wifi/wpa_supplicant.conf
    mkdir /data/local 0751 root root
    mkdir /data/misc/media 0700 media media
    mkdir /data/misc/audioserver 0700 audioserver audioserver
    mkdir /data/misc/cameraserver 0700 cameraserver cameraserver
    mkdir /data/misc/vold 0700 root root
    mkdir /data/misc/boottrace 0771 system shell
    mkdir /data/misc/update_engine 0700 root root
    mkdir /data/misc/update_engine_log 02750 root log
    mkdir /data/misc/trace 0700 root root
    # create location to store surface and window trace files
    mkdir /data/misc/wmtrace 0700 system system
    # profile file layout
    mkdir /data/misc/profiles 0771 system system
    mkdir /data/misc/profiles/cur 0771 system system
    mkdir /data/misc/profiles/ref 0771 system system
    mkdir /data/misc/profman 0770 system shell
    mkdir /data/misc/gcov 0770 root root

    mkdir /data/vendor 0771 root root
    mkdir /data/vendor_ce 0771 root root
    mkdir /data/vendor_de 0771 root root
    mkdir /data/vendor/hardware 0771 root root

    # For security reasons, /data/local/tmp should always be empty.
    # Do not place files or directories in /data/local/tmp
    mkdir /data/local/tmp 0771 shell shell
    mkdir /data/local/traces 0777 shell shell
    mkdir /data/data 0771 system system
    mkdir /data/app-private 0771 system system
    mkdir /data/app-ephemeral 0771 system system
    mkdir /data/app-asec 0700 root root
    mkdir /data/app-lib 0771 system system
    mkdir /data/app 0771 system system
    mkdir /data/property 0700 root root
    mkdir /data/tombstones 0771 system system
    mkdir /data/vendor/tombstones 0771 root root
    mkdir /data/vendor/tombstones/wifi 0771 wifi wifi

    # create dalvik-cache, so as to enforce our permissions
    mkdir /data/dalvik-cache 0771 root root
    # create the A/B OTA directory, so as to enforce our permissions
    mkdir /data/ota 0771 root root

    # create the OTA package directory. It will be accessed by GmsCore (cache
    # group), update_engine and update_verifier.
    mkdir /data/ota_package 0770 system cache

    # create resource-cache and double-check the perms
    mkdir /data/resource-cache 0771 system system
    chown system system /data/resource-cache
    chmod 0771 /data/resource-cache

    # create the lost+found directories, so as to enforce our permissions
    mkdir /data/lost+found 0770 root root

    # create directory for DRM plug-ins - give drm the read/write access to
    # the following directory.
    mkdir /data/drm 0770 drm drm

    # create directory for MediaDrm plug-ins - give drm the read/write access to
    # the following directory.
    mkdir /data/mediadrm 0770 mediadrm mediadrm

    mkdir /data/anr 0775 system system

    # NFC: create data/nfc for nv storage
    mkdir /data/nfc 0770 nfc nfc
    mkdir /data/nfc/param 0770 nfc nfc

    # Create all remaining /data root dirs so that they are made through init
    # and get proper encryption policy installed
    mkdir /data/backup 0700 system system
    mkdir /data/ss 0700 system system

    mkdir /data/system 0775 system system
    mkdir /data/system/heapdump 0700 system system
    mkdir /data/system/users 0775 system system

    mkdir /data/system_de 0770 system system
    mkdir /data/system_ce 0770 system system

    mkdir /data/misc_de 01771 system misc
    mkdir /data/misc_ce 01771 system misc

    mkdir /data/user 0711 system system
    mkdir /data/user_de 0711 system system
    symlink /data/data /data/user/0

    mkdir /data/media 0770 media_rw media_rw
    mkdir /data/media/obb 0770 media_rw media_rw

    mkdir /data/cache 0770 system cache
    mkdir /data/cache/recovery 0770 system cache
    mkdir /data/cache/backup_stage 0700 system system
    mkdir /data/cache/backup 0700 system system

    # Requires vold which is is not needed in Mer
    #init_user0

    # Set SELinux security contexts on upgrade or policy update.
    restorecon --recursive --skip-ce /data

    # Check any timezone data in /data is newer than the copy in /system, delete if not.
    exec - system system -- /system/bin/tzdatacheck /system/usr/share/zoneinfo /data/misc/zoneinfo

    # If there is no post-fs-data action in the init.<device>.rc file, you
    # must uncomment this line, otherwise encrypted filesystems
    # won't work.
    # Set indication (checked by vold) that we have finished this action
    #setprop vold.post_fs_data_done 1

# It is recommended to put unnecessary data/ initialization from post-fs-data
# to start-zygote in device's init.rc to unblock zygote start.
on zygote-start && property:ro.crypto.state=unencrypted
    start netd
    start zygote
    start zygote_secondary

on zygote-start && property:ro.crypto.state=unsupported
    start netd
    start zygote
    start zygote_secondary

on zygote-start && property:ro.crypto.state=encrypted && property:ro.crypto.type=file
    start netd
    start zygote
    start zygote_secondary

on boot
    # basic network init
    ifup lo
# Conflicts with Mer
    #hostname localhost
    #domainname localdomain

    # IPsec SA default expiration length
    write /proc/sys/net/core/xfrm_acq_expires 3600

    # Memory management.  Basic kernel parameters, and allow the high
    # level system server to be able to adjust the kernel OOM driver
    # parameters to match how it is managing things.
    write /proc/sys/vm/overcommit_memory 1
    write /proc/sys/vm/min_free_order_shift 4
    chown root system /sys/module/lowmemorykiller/parameters/adj
    chmod 0664 /sys/module/lowmemorykiller/parameters/adj
    chown root system /sys/module/lowmemorykiller/parameters/minfree
    chmod 0664 /sys/module/lowmemorykiller/parameters/minfree

    # Tweak background writeout
    write /proc/sys/vm/dirty_expire_centisecs 200
    write /proc/sys/vm/dirty_background_ratio  5

    # Permissions for System Server and daemons.
    chown radio system /sys/android_power/state
    chown radio system /sys/android_power/request_state
    chown radio system /sys/android_power/acquire_full_wake_lock
    chown radio system /sys/android_power/acquire_partial_wake_lock
    chown radio system /sys/android_power/release_wake_lock
    chown system system /sys/power/autosleep
    chown system system /sys/power/state
    chown system system /sys/power/wakeup_count
    chown radio wakelock /sys/power/wake_lock
    chown radio wakelock /sys/power/wake_unlock
    chmod 0660 /sys/power/state
    chmod 0660 /sys/power/wake_lock
    chmod 0660 /sys/power/wake_unlock

    chown system system /sys/devices/system/cpu/cpufreq/interactive/timer_rate
    chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/timer_rate
    chown system system /sys/devices/system/cpu/cpufreq/interactive/timer_slack
    chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/timer_slack
    chown system system /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
    chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
    chown system system /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
    chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
    chown system system /sys/devices/system/cpu/cpufreq/interactive/target_loads
    chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/target_loads
    chown system system /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
    chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
    chown system system /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
    chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
    chown system system /sys/devices/system/cpu/cpufreq/interactive/boost
    chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/boost
    chown system system /sys/devices/system/cpu/cpufreq/interactive/boostpulse
    chown system system /sys/devices/system/cpu/cpufreq/interactive/input_boost
    chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/input_boost
    chown system system /sys/devices/system/cpu/cpufreq/interactive/boostpulse_duration
    chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/boostpulse_duration
    chown system system /sys/devices/system/cpu/cpufreq/interactive/io_is_busy
    chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/io_is_busy

    # Assume SMP uses shared cpufreq policy for all CPUs
    chown system system /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
    chmod 0660 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

    # SailfishOS: allow input group to use vibrator
    chown system input /sys/class/leds/vibrator/activate
    chown system input /sys/class/leds/vibrator/duration
    chown system system /sys/class/leds/vibrator/trigger
    chown system system /sys/class/leds/vibrator/brightness
    chown system system /sys/class/leds/vibrator/state
    # SailfishOS: allow input group to use vibrator
    chown system input /sys/class/timed_output/vibrator/enable
    chown system system /sys/class/leds/keyboard-backlight/brightness
    chown system system /sys/class/leds/lcd-backlight/brightness
    chown system system /sys/class/leds/button-backlight/brightness
    chown system system /sys/class/leds/jogball-backlight/brightness
    chown system system /sys/class/leds/red/brightness
    chown system system /sys/class/leds/green/brightness
    chown system system /sys/class/leds/blue/brightness
    chown system system /sys/class/leds/red/device/grpfreq
    chown system system /sys/class/leds/red/device/grppwm
    chown system system /sys/class/leds/red/device/blink
    chown system system /sys/module/sco/parameters/disable_esco
    chown system system /sys/kernel/ipv4/tcp_wmem_min
    chown system system /sys/kernel/ipv4/tcp_wmem_def
    chown system system /sys/kernel/ipv4/tcp_wmem_max
    chown system system /sys/kernel/ipv4/tcp_rmem_min
    chown system system /sys/kernel/ipv4/tcp_rmem_def
    chown system system /sys/kernel/ipv4/tcp_rmem_max
    chown root radio /proc/cmdline

    # Define default initial receive window size in segments.
    setprop net.tcp.default_init_rwnd 60

    # Allow system group to trigger vibrator
    chmod 0664 /sys/class/timed_output/vibrator/enable

    # Start standard binderized HAL daemons
    class_start hal

    class_start core
    class_start main

# Never gets called, since Mer does its own 'mount_all'
on nonencrypted
    class_start main
    class_start late_start

on property:sys.init_log_level=*
    loglevel ${sys.init_log_level}

# Mer needs to set this property when fs units are mounted
on property:droid.late_start=trigger_late_start
    class_start late_start

on charger
    trigger late-init

on property:vold.decrypt=trigger_reset_main
    class_reset main

on property:vold.decrypt=trigger_load_persist_props
    load_persist_props
    start logd
    start logd-reinit

# corefile limit
on property:persist.debug.trace=1
   mkdir /data/core 0777 root root
   write /proc/sys/kernel/core_pattern "/data/core/%E.%p.%e"

on property:vold.decrypt=trigger_post_fs_data
    trigger post-fs-data
    trigger zygote-start

on property:vold.decrypt=trigger_restart_min_framework
    class_start main

on property:vold.decrypt=trigger_restart_framework
    class_start main
    class_start late_start
    setprop service.bootanim.exit 0
    start bootanim

on property:vold.decrypt=trigger_shutdown_framework
    class_reset late_start
    class_reset main

on property:sys.boot_completed=1
    bootchart stop

# system server cannot write to /proc/sys files,
# and chown/chmod does not work for /proc/sys/ entries.
# So proxy writes through init.
on property:sys.sysctl.extra_free_kbytes=*
    write /proc/sys/vm/extra_free_kbytes ${sys.sysctl.extra_free_kbytes}

# "tcp_default_init_rwnd" Is too long!
on property:sys.sysctl.tcp_def_init_rwnd=*
    write /proc/sys/net/ipv4/tcp_default_init_rwnd ${sys.sysctl.tcp_def_init_rwnd}

on property:security.perf_harden=0
    write /proc/sys/kernel/perf_event_paranoid 1

on property:security.perf_harden=1
    write /proc/sys/kernel/perf_event_paranoid 3

# on shutdown
# In device's init.rc, this trigger can be used to do device-specific actions
# before shutdown. e.g disable watchdog and mask error handling

## Daemon processes to be run by init.
##
service ueventd /sbin/ueventd
    class core
    critical
    seclabel u:r:ueventd:s0
    shutdown critical
#Not used by Mer
    disabled

service console /system/bin/sh
    class core
    console
    disabled
    user shell
    group shell log readproc
    seclabel u:r:shell:s0
    setenv HOSTNAME console

on property:ro.debuggable=1
    # Give writes to anyone for the trace folder on debug builds.
    # The folder is used to store method traces.
    chmod 0773 /data/misc/trace
    # Give reads to anyone for the window trace folder on debug builds.
    chmod 0775 /data/misc/wmtrace
    start console

service flash_recovery /system/bin/install-recovery.sh
    class main
    oneshot

# This trigger is run by our modified init after boot has finished
on ready
    class_start mer

# Notify Mer's systemd that we're done
# This is started at the end of boot after both core and main classes
service droid_init_done /bin/sh /usr/bin/droid/droid-init-done.sh
    class mer
    oneshot

# Properly handle shutdown from Mer
on property:hybris.shutdown=*
    class_stop late_start
    class_stop main
    class_stop core
[nemo@Pro1 ~]$ ls -lh /sys/class/timed_output/vibrator/
total 0      
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 auto_res_mode
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 calib_period
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 dump_regs
-rw-rw-r--    1 system   system      4.0K Jul 21 18:19 enable
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 high_z_period
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 min_max_test
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 override_auto_mode_config
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 play_mode
drwxr-xr-x    2 root     root           0 Jul 21 19:25 power
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 ramp_test
lrwxrwxrwx    1 root     root           0 Jul 21 18:19 subsystem -> ../../../../class/timed_output
-rw-r--r--    1 root     root        4.0K Jul 21 18:19 uevent
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 vmax_mv
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 wf_rep
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 wf_s0
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 wf_s1
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 wf_s2
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 wf_s3
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 wf_s4
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 wf_s5
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 wf_s6
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 wf_s7
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 wf_s_rep
-rw-rw-r--    1 root     root        4.0K Jul 21 19:25 wf_update
[nemo@Pro1 ~]$ rpm -qi aliendalvik
Name        : aliendalvik
Version     : 8.1.0.73.6
Release     : 1.13.1.jolla
Architecture: armv7hl
Install Date: Sat Jun 13 13:34:54 2020
Group       : System/GUI/Other/Packages
Size        : 282669775
License     : Myriad Group AG.
Signature   : DSA/SHA1, Tue Mar 10 21:46:57 2020, Key ID 68ebdd7df2633ee0
Source RPM  : aliendalvik-8.1.0.73.6-1.13.1.jolla.src.rpm
Build Date  : Tue Mar 10 21:44:58 2020
Build Host  : phost10
Relocations : (not relocatable)
Vendor      : meego
Summary     : Myriad Alien Dalvik with upgraded Android Runtime
Description :
Myriad Alien Dalvik with upgraded Android Runtime
```

**Comment by schmittlauch** [comment]
So somehow the lines 
```
# SailfishOS: allow input group to use vibrator
chown system input /sys/class/timed_output/vibrator/enable
``` 

in the on-boot section are not triggered properly causing `/sys/class/timed_output/vibrator/enable` to still be owned by `system:system`.

I could try to chown it manually.

**Comment by piggz** [comment]
Your problem is aliendalvik
Turn it off from starting on startup and reboot, your vibration should then be working.
Ive heard that it is fixed in a later version of AD, but, if you turn it off and start an android app afterwards, vibration will work, atleast it is here

**Comment by piggz** [comment]
To summarise further .... in ye olde times, nemo was a member of system and all was well ..... except it wasnt great for security.  In the latest sfos, nemo is no longer in system, and a patch was required to set the vibration to group input to allow nemo to use it.  This is what I added in the latest devel release.  The AD version however resets the group back to system before the nemo processes have opened the file. By setting AD to not auto start, nemo can open the file, and when AD starts, it doesnt matter that the ownership changes.  As AD isnt supported on community ports, you'll have to live with it as-is until you can get a fixed version of AD.

Hope that explains it all!

**Comment by Kabouik** [comment]
That's weird because I have AD too and the groups are not reset for me, and when I lost vibration with a fresh image flash, then AD was not installed.

**Comment by schmittlauch** [comment]
I can confirm that disabling AlienDalvik autostart fixes this for me though.

**Comment by schmittlauch** [comment]
> when I lost vibration with a fresh image flash, then AD was not installed.

That's because the fresh image was from the testing repos, and the fix for `input` ownership was just released in the devel repos.

Maybe you also have a newer AD version?

**Comment by piggz** [comment]
@Kabouik you restored from a backup and still have nemo in system group dont you?  There is no image built with the fix in yet, its just in the repos.

**Comment by piggz** [comment]
@schmittlauch as you are now on devel, you can also enjoy BT calling

**Comment by schmittlauch** [comment]
I'd say we can close this now with "AlienDalvik is not supported but is the cause for this".
Thanks.

**Comment by piggz** [comment]
@schmittlauch is your camera now broken?

**Comment by schmittlauch** [comment]
@piggz Luckily no.

Fingerprint unlocking doesn't work yet, but I'm sceptical of biometrics as *the only factor* anyways.

**Comment by piggz** [comment]
phew, only my camera is broken then, i wonder why!! biometrics is always another factor, pin can always be used.

**Comment by Kabouik** [comment]
Yes, nemo still in system group. I do have a recent AD, I think the update that came with SFOS 3.3. So do I understand well that "AD is not supported but is the cause for this issue unless you use the latest AD version"?

**Comment by piggz** [comment]
AD is the cause of the issue after I fixed the actual problem in the latest builds, which was the vibration sys file being the wrong group.  You can still use the faulty AD and have vibration by stopping AD starting automatically on boot.

**Comment by Kabouik** [comment]
> You can still use the faulty AD and have vibration **by stopping AD starting automatically on boot**.

Or by updating AD to the latest version ← Is that correct?

**Comment by piggz** [comment]
Yes, however I dont know the version number of the fixed version, and cant support AD in a community port anyway ;)
