### ISSUE TITLE
Media playback not working

### ISSUE THREAD

**Issue by piggz** [sailfish-on-fxtecpro1/droid-config-t5#5]

**Comment by piggz** [comment]
Fixed with added firmware symlink /firmware > /vendor/firmware_mnt/

**Comment by Kabouik** [comment]
The symlink is there but I still cannot play any video, local or distant (see #25).

[nemo@Sailfish ~]$ ls /firmware/
image  verinfo
[nemo@Sailfish ~]$ ls /vendor/firmware_mnt/
image  verinfo
